import { prisma } from '../../../lib/db';
import { invoiceStatusLabel } from '../../../lib/invoice-display';
import { markOverdueInvoices } from '../../../server/services/invoices';
import { ManualPaymentForm } from '../../../components/finance/manual-payment-form';
import { ManualPaymentHistory } from '../../../components/finance/manual-payment-history';
import { PaymentReminderButton } from '../../../components/finance/payment-reminder-button';
import { getSessionUser } from '../../../lib/auth';
import { redirect } from 'next/navigation';
export default async function FinancePage(){if((await getSessionUser())?.role!=='ADMIN')redirect('/admin');await markOverdueInvoices();const [invoices,enrollments,payments]=await Promise.all([prisma.invoice.findMany({include:{enrollment:{include:{student:true,plan:true}}},orderBy:{dueDate:'asc'}}),prisma.enrollment.findMany({where:{status:{not:'CANCELED'}},include:{student:true,plan:true},orderBy:{student:{fullName:'asc'}}}),prisma.manualPayment.findMany({include:{enrollment:{include:{student:true}}},orderBy:{receivedAt:'desc'}})]);const groups:Array<typeof invoices>=Object.values(invoices.reduce<Record<string,typeof invoices>>((all:Record<string,typeof invoices>,invoice:(typeof invoices)[number])=>{(all[invoice.enrollment.student.fullName]??=[]).push(invoice);return all;},{})) as Array<typeof invoices>;return <section><p className="text-sm font-semibold text-emerald-700">Financeiro</p><h1 className="mt-1 text-3xl font-bold">Mensalidades</h1><p className="my-3 text-slate-600">Confirme pagamentos presenciais por Pix, Dinheiro ou Cartão.</p><ManualPaymentForm enrollments={enrollments}/><section className="mt-6 overflow-hidden rounded-xl border bg-white"><h2 className="p-4 font-bold">Mensalidades por aluno</h2>{groups.length?groups.map((items:(typeof groups)[number])=>{const first=items[0];const paid=items.filter((item:(typeof items)[number])=>item.status==='PAID').length;return <details className="border-t" key={first.enrollment.student.fullName}><summary className="cursor-pointer list-none p-4 hover:bg-slate-50"><strong>{first.enrollment.student.fullName}</strong><span className="ml-3 text-sm text-slate-600">{first.enrollment.plan.name} · {paid}/{items.length} mensalidades pagas · Ver mensalidades</span></summary>{items.map((invoice:(typeof items)[number])=><article className="border-t px-4 py-3" key={invoice.id}><p className="text-sm text-slate-600">{invoice.referenceMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} · <span className={invoice.status==='PAID'?'text-emerald-700':'text-amber-700'}>{invoiceStatusLabel(invoice.status)}</span></p><p className="font-semibold">R$ {(invoice.amountCents/100).toFixed(2).replace('.',',')}<PaymentReminderButton student={invoice.enrollment.student} dueDate={invoice.dueDate}/></p></article>)}</details>}):<p className="border-t p-5 text-slate-600">Nenhuma mensalidade gerada ainda.</p>}</section><ManualPaymentHistory payments={payments}/></section>}
