'use client';
import { useEffect, useState } from 'react';
type Occurrence = { id: string; startsAt: string; capacity: number; occupied: number; bookingId:string|null };
const format = (value: string) => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export function BookingCalendar() {
  const [items, setItems] = useState<Occurrence[]>([]); const [message, setMessage] = useState(''); const [bookingToChange,setBookingToChange]=useState<string|null>(null); const [makeupMode,setMakeupMode]=useState(false); const [makeupCredits,setMakeupCredits]=useState(0);
  async function load() { const response = await fetch('/api/student/bookings'); if (response.ok) { const data=await response.json(); setItems(data.occurrences); setMakeupCredits(data.makeupCredits); } }
  useEffect(() => { void load(); }, []);
  async function reserve(occurrenceId: string) { const response = await fetch('/api/student/bookings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ occurrenceId, kind: makeupMode?'MAKEUP':'REGULAR' }) }); setMessage(response.ok ? (makeupMode?'Reposição confirmada.':'Reserva confirmada.') : (makeupMode?'Não foi possível usar a reposição: verifique a vaga disponível.':'Não foi possível reservar: vaga, plano ou limite semanal.')); if (response.ok) {setMakeupMode(false);void load();} }
  async function cancel(bookingId:string){const response=await fetch(`/api/student/bookings/${bookingId}`,{method:'DELETE'});setMessage(response.ok?'Reserva cancelada; você pode escolher outro horário.':'A alteração só pode ser feita até 2 horas antes da aula.');if(response.ok)void load();}
  async function swap(targetOccurrenceId:string){if(!bookingToChange)return;const response=await fetch(`/api/student/bookings/${bookingToChange}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({targetOccurrenceId})});setMessage(response.ok?'Horário alterado com sucesso.':'Não foi possível trocar: verifique a vaga, o plano e o prazo de 2 horas.');if(response.ok){setBookingToChange(null);void load();}}
  const days=[['Segunda-feira',1],['Terça-feira',2],['Quarta-feira',3],['Quinta-feira',4]] as const;const card=(item:Occurrence)=><article className="rounded-xl border bg-white p-5" key={item.id}><p className="text-xl font-bold capitalize">{format(item.startsAt)}</p><p className="mt-2 text-base text-slate-600">{item.capacity-item.occupied} vagas disponíveis</p>{item.bookingId?<span className="mt-4 flex flex-col gap-3"><button className="rounded-lg bg-emerald-700 px-4 py-3 text-base font-bold text-white" onClick={()=>setBookingToChange(item.bookingId!)}>Trocar esta aula</button><button className="text-base font-semibold text-amber-800" onClick={()=>cancel(item.bookingId!)}>Cancelar aula</button></span>:<button className="mt-4 w-full rounded-lg bg-emerald-700 px-4 py-3 text-base font-bold text-white disabled:opacity-50" disabled={item.occupied>=item.capacity} onClick={()=>bookingToChange?swap(item.id):reserve(item.id)}>{bookingToChange?'Escolher esta data e horário':makeupMode?'Usar reposição neste horário':'Reservar esta aula'}</button>}</article>;return <div className="grid gap-4">{makeupCredits?<section className="rounded-xl bg-emerald-50 p-4 text-base"><strong>Você tem {makeupCredits} reposição(ões) disponível(is).</strong><button className="mt-3 block rounded-lg border border-emerald-700 px-4 py-2 font-bold text-emerald-800" onClick={()=>setMakeupMode(value=>!value)}>{makeupMode?'Cancelar reposição':'Usar uma reposição'}</button></section>:null}{bookingToChange?<p className="rounded-xl bg-amber-50 p-4 text-base font-medium text-amber-900">Escolha abaixo uma nova data e horário com vaga livre.</p>:null}{makeupMode?<p className="rounded-xl bg-amber-50 p-4 text-base font-medium text-amber-900">Escolha uma aula com vaga livre para usar sua reposição.</p>:null}{days.map(([name,day])=>{const dayItems=items.filter(item=>new Date(item.startsAt).getDay()===day);return <details className="rounded-xl border bg-white" key={day}><summary className="cursor-pointer p-5 text-xl font-bold">{name} · {dayItems.length} horário(s)</summary><div className="grid gap-4 border-t p-4">{dayItems.length?dayItems.map(card):<p className="text-base text-slate-600">Não há horários disponíveis neste dia.</p>}</div></details>})}{message?<p aria-live="polite" className="rounded-lg bg-slate-100 p-3 text-base">{message}</p>:null}</div>;
}
