'use client';
import { useEffect, useState } from 'react';
type Occurrence = { id: string; startsAt: string; capacity: number; occupied: number; bookingId:string|null };
const format = (value: string) => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export function BookingCalendar() {
  const [items, setItems] = useState<Occurrence[]>([]); const [message, setMessage] = useState(''); const [bookingToChange,setBookingToChange]=useState<string|null>(null);
  async function load() { const response = await fetch('/api/student/bookings'); if (response.ok) setItems(await response.json()); }
  useEffect(() => { void load(); }, []);
  async function reserve(occurrenceId: string) { const response = await fetch('/api/student/bookings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ occurrenceId }) }); setMessage(response.ok ? 'Reserva confirmada.' : 'Não foi possível reservar: vaga, plano ou limite semanal.'); if (response.ok) void load(); }
  async function cancel(bookingId:string){const response=await fetch(`/api/student/bookings/${bookingId}`,{method:'DELETE'});setMessage(response.ok?'Reserva cancelada; você pode escolher outro horário.':'A alteração só pode ser feita até 2 horas antes da aula.');if(response.ok)void load();}
  async function swap(targetOccurrenceId:string){if(!bookingToChange)return;const response=await fetch(`/api/student/bookings/${bookingToChange}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({targetOccurrenceId})});setMessage(response.ok?'Horário alterado com sucesso.':'Não foi possível trocar: verifique a vaga, o plano e o prazo de 2 horas.');if(response.ok){setBookingToChange(null);void load();}}
  return <div className="grid gap-3">{bookingToChange?<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Selecione um horário disponível abaixo para concluir a troca. Sua vaga atual só será liberada após a confirmação.</p>:null}{items.map((item) => <article className="rounded-xl border bg-white p-4" key={item.id}><p className="font-semibold capitalize">{format(item.startsAt)}</p><p className="mt-1 text-sm text-slate-600">{item.capacity - item.occupied} vagas disponíveis</p>{item.bookingId?<span className="mt-3 flex gap-3"><button className="text-sm font-semibold text-emerald-700" onClick={() => setBookingToChange(item.bookingId!)}>Trocar horário</button><button className="text-sm text-amber-800" onClick={() => cancel(item.bookingId!)}>Cancelar</button></span>:<button className="mt-3 rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={item.occupied >= item.capacity} onClick={() => bookingToChange?swap(item.id):reserve(item.id)}>{bookingToChange?'Trocar para este horário':'Reservar'}</button>}</article>)}{message ? <p aria-live="polite">{message}</p> : null}{!items.length ? <p className="text-slate-600">Nenhum horário disponível.</p> : null}</div>;
}
